### ISSUE TITLE
PBS 라이브러리화 가능할까?

### ISSUE THREAD

**Issue by tuxedcat** [tuxedcat/pslib#10]
boj.kr/5820

**Comment by 0xC0DEF** [comment]
boj.kr/5542

**Comment by 0xC0DEF** [comment]
센트로이드 완료

**Comment by tuxedcat** [comment]
pbs 이해만하면 그냥 오프라인쿼리+스위핑이라 굳이 라이브러리화할 코드가 없는거같다.
https://blog.tuxedcat.com/all/Algorithm/%EB%B6%84%EB%A5%98/DnC/PBS.html
